# Generated by Django 6.0.6 on 2026-07-23 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('original_file', models.FileField(upload_to='datasets/original/')),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='datasets/cleaned/')),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('rows_count', models.IntegerField(blank=True, null=True)),
                ('cols_count', models.IntegerField(blank=True, null=True)),
                ('memory_usage', models.CharField(blank=True, max_length=50, null=True)),
                ('encoding', models.CharField(default='UTF-8', max_length=50)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cleaning_config', models.JSONField(default=dict)),
                ('before_stats', models.JSONField(default=dict)),
                ('after_stats', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('rows_removed', models.IntegerField(default=0)),
                ('cols_removed', models.IntegerField(default=0)),
                ('missing_filled', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to='cleaning.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['user', 'is_deleted'], name='cleaning_da_user_id_d8b733_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['uuid'], name='cleaning_da_uuid_0887a6_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['created_at'], name='cleaning_da_created_383da0_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningjob',
            index=models.Index(fields=['user', 'is_deleted'], name='cleaning_cl_user_id_5a8600_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningjob',
            index=models.Index(fields=['uuid'], name='cleaning_cl_uuid_2df8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningjob',
            index=models.Index(fields=['created_at'], name='cleaning_cl_created_227c45_idx'),
        ),
    ]
