# Generated by Django 6.0.6 on 2026-07-07 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='datasets/original/')),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='datasets/cleaned/')),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('rows_count', models.IntegerField(blank=True, null=True)),
                ('cols_count', models.IntegerField(blank=True, null=True)),
                ('memory_usage', models.CharField(blank=True, max_length=50, null=True)),
                ('encoding', models.CharField(default='UTF-8', max_length=50)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_config', models.JSONField(default=dict)),
                ('before_stats', models.JSONField(default=dict)),
                ('after_stats', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_jobs', to='cleaning.dataset')),
            ],
        ),
    ]
