# Generated by Django 6.0.6 on 2026-07-23 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('target_column', models.CharField(max_length=100)),
                ('selected_features', models.JSONField(default=list)),
                ('selected_models', models.JSONField(default=list)),
                ('training_mode', models.CharField(default='manual', max_length=50)),
                ('preprocessing_steps', models.JSONField(default=list)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('evaluation_metrics', models.JSONField(default=dict)),
                ('best_model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('best_model_score', models.FloatField(blank=True, null=True)),
                ('training_duration', models.FloatField(default=0.0)),
                ('prediction_duration', models.FloatField(default=0.0)),
                ('trained_model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('predictions', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('progress_stage', models.CharField(default='initialized', max_length=100)),
                ('progress_percent', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_training_jobs', to='cleaning.dataset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_training_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
