# Generated by Django 6.0.6 on 2026-08-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingjob',
            name='feature_dtypes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
