# Generated by Django 6.0.6 on 2026-08-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0002_modeltrainingjob_feature_dtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingjob',
            name='feature_encodings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
