# Generated by Django 6.0.6 on 2026-07-23 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('dataset_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('graph_type', models.CharField(max_length=100)),
                ('library', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('python_code', models.TextField(blank=True, default='')),
                ('preview_data', models.TextField(blank=True, default='')),
                ('download_count', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_graphs', to='cleaning.dataset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_graphs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_deleted'], name='visualizati_user_id_7f852b_idx'), models.Index(fields=['uuid'], name='visualizati_uuid_4a3d7c_idx'), models.Index(fields=['created_at'], name='visualizati_created_15d25c_idx')],
            },
        ),
    ]
